<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>none</AnalysisLevel>
  </PropertyGroup>

 

  <ItemGroup>
    <Compile Remove="wwwroot\vendors\%40coreui\**" />
    <Compile Remove="wwwroot\vendors\chart.js\**" />
    <Content Remove="wwwroot\vendors\%40coreui\**" />
    <Content Remove="wwwroot\vendors\chart.js\**" />
    <EmbeddedResource Remove="wwwroot\vendors\%40coreui\**" />
    <EmbeddedResource Remove="wwwroot\vendors\chart.js\**" />
    <None Remove="wwwroot\vendors\%40coreui\**" />
    <None Remove="wwwroot\vendors\chart.js\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controllers\AlunoesController.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
  </ItemGroup>

</Project>
